### accuracy
### sensitivity
### precision
### specificity
### F1-score

In [21]:
import pandas as pd

In [29]:
predicted_df = pd.read_csv("DeePred-BBB_predictions.csv")

In [30]:
predicted_df

                                                   Name  Predicted_class
0                                  s1cc(nc1[NH]=C(N)N)C              1.0
1                                          s1c(ncc1)CCN              1.0
2                                S=C2NCCC(COc1ccccc1)O2              1.0
3                                S=P(N1CC1)(N2CC2)N3CC3              1.0
4                 s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N              1.0
...                                                 ...              ...
3600                       [C@H](C)(n1c(C)ncc1)c1ccccc1              1.0
3601  [Cl]/C1=C/C(=C/C=C1/[Cl])CC(=O)N2CC[C@@]4(C[C@...              0.0
3602     [C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1              1.0
3603  C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(...              1.0
3604  C[C@@]1([H])O[C@@]([H])(C[C@@](O)([H])[C@@]1(O...              1.0

[3605 rows x 2 columns]

In [31]:
true_df = pd.read_excel("Table 1.xlsx")

In [32]:
true_df

,SL,Compounds,PID,BBB-Class,References,Unnamed: 5,Unnamed: 6
0,1,SCC(=O)[C@@]1(O)[C@@]2(C)[C@H]([C@H]3[C@H]([C@...,NaN,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,BBB-Class 1: Permeable
1,2,s1cc(nc1[NH]=C(N)N)C,6928896,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,BBB-Class 0: Non-permeable
2,3,s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N,NaN,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
3,4,s1c(ncc1)CCN,87653,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
4,5,S=P(N1CC1)(N2CC2)N3CC3,5453,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
...,...,...,...,...,...,...,...
3600,3601,[C@H]1(c2ccccc2)[N@]2[C@@H](NC1)NCC2,NaN,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3601,3602,[C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1,14208378,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3602,3603,[C@H](CCC)(Cc1ccccc1)N1CCCC1,54153082,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3603,3604,[C@H](CCC)(CC)C,13800357,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3604,3605,[C@H](C)(n1c(C)ncc1)c1ccccc1,76960079,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN

In [33]:
merged_df = predicted_df.merge(true_df, left_on='Name', right_on = 'Compounds')

In [34]:
merged_df

,Name,Predicted_class,SL,Compounds,PID,BBB-Class,References,Unnamed: 5,Unnamed: 6
0,s1cc(nc1[NH]=C(N)N)C,1.0,2,s1cc(nc1[NH]=C(N)N)C,6928896,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,BBB-Class 0: Non-permeable
1,s1c(ncc1)CCN,1.0,4,s1c(ncc1)CCN,87653,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
2,S=C2NCCC(COc1ccccc1)O2,1.0,6,S=C2NCCC(COc1ccccc1)O2,3033964,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
3,S=P(N1CC1)(N2CC2)N3CC3,1.0,5,S=P(N1CC1)(N2CC2)N3CC3,5453,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
4,s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N,1.0,3,s1cc(CSCCNC(NC)=[NH]C#N)nc1[NH]=C(N)N,NaN,1,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3608,[C@H](C)(n1c(C)ncc1)c1ccccc1,1.0,3605,[C@H](C)(n1c(C)ncc1)c1ccccc1,76960079,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3609,[Cl]/C1=C/C(=C/C=C1/[Cl])CC(=O)N2CC[C@@]4(C[C@...,0.0,3597,[Cl]/C1=C/C(=C/C=C1/[Cl])CC(=O)N2CC[C@@]4(C[C@...,NaN,0,Shen et al. J Chem Inf Model. 2010;50(6):1034...,NaN,NaN
3610,[C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1,1.0,3602,[C@H]1([C@@H]2NCCCC2)OC(c2ccccc2)(c2ccccc2)OC1,14208378,1,Roy et al. ACS Omega. 2019; 4(16):16774-16780....,NaN,NaN
3611,C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(...,1.0,3535,C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(...,2283,0,Zhao et al. J Chem Inf Model. 2007;47(1):170–...,NaN,NaN
3612,C[C@@]1([H])O[C@@]([H])(C[C@@](O)([H])[C@@]1(O...,1.0,3500,C[C@@]1([H])O[C@@]([H])(C[C@@](O)([H])[C@@]1(O...,2724385,0,Shen et al. J Chem Inf Model. 2010;50(6):1034...,NaN,NaN

In [26]:
merged_df.loc[3611, 'Name']

'C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(NC(C(N1)=O)C(CC)C)=O)CCCN)=O)CCCCNC(C(NC(C(NC(C(NC(C1N=C(C(C(CC)C)N)SC1)=O)CC(C)C)=O)CCC(O)=O)=O)C(CC)C)=O)CC(N)=O)=O)CC(O)=O)=O)=O)c1ccccc1'

In [28]:
merged_df.iloc[3611][0]

/var/folders/16/gzssnc2x4qz5n4rkpvt7tsjh0000gn/T/ipykernel_4857/3783982151.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  merged_df.iloc[3611][0]

'C(C1C(NC(Cc2c[nH]cn2)C(NC(C(NC(C(=O)NC(C(NC(C(NC(C(N1)=O)C(CC)C)=O)CCCN)=O)CCCCNC(C(NC(C(NC(C(NC(C1N=C(C(C(CC)C)N)SC1)=O)CC(C)C)=O)CCC(O)=O)=O)C(CC)C)=O)CC(N)=O)=O)CC(O)=O)=O)=O)c1ccccc1'

In [35]:
true_positive = ((merged_df['BBB-Class'] == 1) & (merged_df['Predicted_class'] == 1)).sum()
true_positive

1509

In [36]:
false_positive = ((merged_df['BBB-Class'] == 0) & (merged_df['Predicted_class'] == 1)).sum()
false_positive

272

In [37]:
precision = true_positive / (true_positive + false_positive)
precision

0.8472768107804605

In [38]:
false_negative = ((merged_df['BBB-Class'] == 1) & (merged_df['Predicted_class'] == 0)).sum()
false_negative

1014

In [39]:
recall = true_positive / (true_positive + false_negative)
recall

0.5980975029726516

In [18]:
(2 * precision * recall)/(precision + recall)

0.7012081784386618

In [19]:
(merged_df['BBB-Class'] == 1).sum()

2615

In [20]:
(merged_df['BBB-Class'] == 0).sum()

998